apiVersion: v1
kind: Service
metadata:
  name: {{ include "sle.fullname" . }}
  labels:
    {{- include "sle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: sle
    {{- range .Values.service.additionalPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  selector:
    {{- include "sle.selectorLabels" . | nindent 4 }}
