replicaCount: 1

image:
  repository: ghcr.io/spacecompute/mission-control-systems/sle
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5100

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

extraEnv: []

extraVolumes: []
extraVolumeMounts: []
