apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openmct.fullname" . }}-entrypoint
  labels:
    {{- include "openmct.labels" . | nindent 4 }}
data:
  entrypoint.sh: |
    {{- .Values.entrypoint | nindent 4 }}
---
{{- range $name, $vol := .Values.volumes }}
{{- if and $vol.enabled (eq ($vol.type | default "emptyDir") "configMap") $vol.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openmct.fullname" $ }}-{{ $name }}
  labels:
    {{- include "openmct.labels" $ | nindent 4 }}
data:
  {{- range $key, $content := $vol.data }}
  {{ $key }}: |
    {{- $content | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
