apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openmct.fullname" . }}
  labels:
    {{- include "openmct.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openmct.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openmct.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: openmct
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          env:
            - name: YAMCS_INSTANCE
              value: {{ .Values.env.YAMCS_INSTANCE | quote }}
            - name: YAMCS_PROCESSOR
              value: {{ .Values.env.YAMCS_PROCESSOR | quote }}
            - name: YAMCS_FOLDER
              value: {{ .Values.env.YAMCS_FOLDER | quote }}
          {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
