apiVersion: v1
kind: Service
metadata:
  name: {{ include "openmct.fullname" . }}
  labels:
    {{- include "openmct.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    {{- range .Values.service.additionalPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  selector:
    {{- include "openmct.selectorLabels" . | nindent 4 }}
