apiVersion: v2
name: mission-control
description: An umbrella chart for deploying the complete Mission Control Systems stack
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: jupyter
    version: 0.1.0
    repository: "file://../jupyter"
  - name: openmct
    version: 0.1.0
    repository: "file://../openmct"
  - name: sle
    version: 0.1.0
    repository: "file://../sle"
  - name: yamcs
    version: 0.1.0
    repository: "file://../yamcs"
